#!/bin/sh

. "$HOME/.guiprofile"

export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
#export SDL_VIDEODRIVER=wayland
export SVDIR=~/runit/wlservice
export XDG_CURRENT_DESKTOP=sway

# /usr/libexec/xdg-desktop-portal-wlr &
# /usr/libexec/xdg-desktop-portal &

. "$HOME/.config/m/$(hostname)/.wlprofile"
