#!/bin/bash

set -eux

fd -e flac -x music-conv-shim "{}" opus -c:v copy -c:a libopus -b:a 128K

fd . -i -e png -e jpg -e jpeg -i -E opus -x bash -c 'echo "$1"; mkdir -p "opus/$(dirname "$1")"; cp "$1" "opus/$(dirname "$1")"' shell {} ';'
