#!/usr/bin/bash

# $1 = Input file
# $2 = Output extension
# $3+ = FFMpeg args

# fullfile="$1"
filename="${1##*/}"
filename="${filename%.*}.$2"
fulldir=$(dirname "${1}")
# reldir="$(echo $fulldir | cut -d'/' -f5-)"
outdir="${2}/${fulldir}"
outfile="${outdir}/${filename}"
mkdir -p "${outdir}"

# echo Relative dir: "$reldir"
echo Output file: "$outfile"
echo FFMpeg args: "${@:3}"

ffmpeg -i "$1" "${@:3}" "${outfile}"
