#!/bin/sh

alias ls='ls --color=never'
alias ll='ls -lah --color=never'
alias rsync='rsync --progress -r'
alias htop='htop'
alias gs='git status'
alias gcm='git commit'
alias gco='git_checkout'
alias grb='git rebase'
alias gre='git remote'
alias gpl='git pull'
alias gps='git push'
alias mkdir='mkdir -p'
alias pstop='podman_stop'

alias open='xdg-open'
alias dnf='dnf5'

# Error correction

alias daos='doas'
alias sduo='sudo'


# Programs that I don't want to install

alias butane='podman run --rm --tty --interactive \
              --security-opt label=disable        \
              --volume ${PWD}:/pwd --workdir /pwd \
              quay.io/coreos/butane:release'

alias phpstan='podman run -v "$PWD:/app" --rm ghcr.io/.phpstan/phpstan'
