#!/bin/sh

#alias sudo='doas'
alias clang='clang'
alias ll='ls -lah'
alias cp='rsync -avh --no-compress --progress'
alias htop='htop'
alias gs='git status'
alias gcm='git commit'
alias gco='git checkout'
alias grb='git rebase'
alias gre='git remote'
alias gpl='git pull'
alias gps='git push'
alias mkdir='mkdir -p'

# Error correction

alias daos='doas'
alias sduo='sudo'


# Programs that I don't want to install

alias butane='podman run --rm --tty --interactive \
              --security-opt label=disable        \
              --volume ${PWD}:/pwd --workdir /pwd \
              quay.io/coreos/butane:release'
