#!/bin/sh

chk_current_sh() {
    if [ $(basename "$SHELL") != "$1" ]; then
	echo "[$1] "
    else
	echo ""
    fi
}

cdlastex() {
    cd "$(cat .lastexer)" || return
}

p() {
    cd "$(select-prj)" || return
}

wlinit() {
    . "$HOME/.wlprofile"

    exec dbus-run-session -- runsvdir -P "$HOME/runit/wlservice"
}

maskpath() {
    export PS1='%B%%%b '
}

vagrant(){
  podman run -it --rm \
    -e LIBVIRT_DEFAULT_URI \
    -v /var/run/libvirt/:/var/run/libvirt/ \
    -v ~/.vagrant.d/boxes:/vagrant/boxes \
    -v ~/.vagrant.d/data:/vagrant/data \
    -v ~/.vagrant.d/data:/vagrant/tmp \
    -v $(realpath "${PWD}"):${PWD} \
    -w $(realpath "${PWD}") \
    --network host \
    --entrypoint /bin/bash \
    --security-opt label=disable \
    docker.io/vagrantlibvirt/vagrant-libvirt:latest \
      vagrant $@
}
