#!/bin/sh

chk_current_sh() {
    if [ $(basename "$SHELL") != "$1" ]; then
	echo "[$1] "
    else
	echo ""
    fi
}

cdlastex() {
    cd "$(cat .lastexer)" || return
}

p() {
    cd "$(select-prj)" || return
}

maskpath() {
    export PS1='%B%%%b '
}

git_checkout() {
    branch=$(git branch --all | fzf | sed "s/remotes\/origin\///" | xargs)
    if [ "${branch}" ]; then
        git checkout "${branch}"
    fi
}

podman_stop() {
    id=$(podman ps | tail -n -1 | fzf | awk '{ print $1; }')
    podman stop "${id}"
}

check_ns() {
    for ns in 1.1.1.1 8.8.8.8 9.9.9.9; do
        dig "${1:-a}" +short @${ns} "${2:-suzunaan.org}"
    done
}
